In [2]:
#This notebook is a tutorial on the basic functionality of the pandas library

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import datasets # example datasets in sklearn library

In [26]:
#Before getting into pandas functionality we will load an example dataset from sklearn library 
iris = datasets.load_iris() #load iris dataset
type(iris) #iris is a bunch instance which is inherited from dictionary

sklearn.utils.Bunch

In [20]:
iris.keys() #keys of the dictionary

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [23]:
#The description of the dataset. We see that the dataset has 4 features and a 3 classes.
#There are 150 examples in the dataset
print(iris.DESCR) 

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [25]:
#The feature values are stored under the key 'data' and it is an np.array
type(iris.data)

numpy.ndarray

In [29]:
#each row of this array correspond to an example data point and each column corresponds to a feature
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [33]:
#The feature name corresponding to each column is stored in 'feature_names'
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [30]:
#The classes of each data point is stored in the 'target' key
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [32]:
#The name of the classes corresponding to 0,1,2 can be found in
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [42]:
#Now we are ready to create a pandas dataframe using the iris dataset
#We will do this in two different ways:
# 1-Creating a dataframe from an np.array
# 2-Creating a dataframe from a .csv file

# 1- To create a dataframe from an np.array simply call pd.DataFrame(array) 
iris_dataframe = pd.DataFrame(iris.data)
iris_dataframe.head() #first five data points

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [49]:
#As you see above the feature names are set as 0,1,2,3. We can change them as follows
iris_dataframe.columns = iris.feature_names
# we could also do this when we are creating the data frame as follows
#iris_dataframe = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_dataframe.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [52]:
# Now we want to add the classes of each data point as a new column:
iris_dataframe['target'] = iris.target
iris_dataframe.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [56]:
# You can get a column of a dataframe by using the dot notation
iris_dataframe['sepal length (cm)']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal length (cm), Length: 150, dtype: float64

In [61]:
#Another way to create a data frame is reading from a .csv file. For this we first export the
#dataframe we created to a .csv file and then create a new data frame by reading the same file.
#We will use to_csv function. Setting the index and header parameters to False prevent the 
#index and header written on file.
iris_dataframe.to_csv('iris.csv', index=False, header = False)

In [62]:
ls

__notebook_source__.ipynb  iris.csv


In [66]:
#Now we will create a new data frame using read_csv() function. We will pass the path of the file
#to this function together with the names parameter. See the documentation for details.
columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class']
iris_dataframe_new = pd.read_csv('iris.csv', names = ['sepal length', 'sepal width', 'petal length', 'petal width', 'class'])
iris_dataframe_new.head()

sepal length  sepal width  petal length  petal width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [71]:
iris_dataframe_new.index

RangeIndex(start=0, stop=150, step=1)

In [72]:
iris_dataframe_new.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'class'], dtype='object')

In [77]:
#you can sort the data according to a particular column
iris_dataframe_new.sort_values(by = 'sepal width')

sepal length  sepal width  petal length  petal width  class
60            5.0          2.0           3.5          1.0      1
62            6.0          2.2           4.0          1.0      1
119           6.0          2.2           5.0          1.5      2
68            6.2          2.2           4.5          1.5      1
41            4.5          2.3           1.3          0.3      0
53            5.5          2.3           4.0          1.3      1
93            5.0          2.3           3.3          1.0      1
87            6.3          2.3           4.4          1.3      1
81            5.5          2.4           3.7          1.0      1
80            5.5          2.4           3.8          1.1      1
57            4.9          2.4           3.3          1.0      1
72            6.3          2.5           4.9          1.5      1
146           6.3          2.5           5.0          1.9      2
98            5.1          2.5           3.0          1.1      1
113           5.7          2.5           5.0          2.0      2
108           6.7          2.5           5.8          1.8      2
69            5.6          2.5           3.9          1.1      1
89            5.5          2.5           4.0          1.3      1
106           4.9          2.5           4.5          1.7      2
92            5.8          2.6           4.0          1.2      1
79            5.7          2.6           3.5          1.0      1
90            5.5          2.6           4.4          1.2      1
118           7.7          2.6           6.9          2.3      2
134           6.1          2.6           5.6          1.4      2
101           5.8          2.7           5.1          1.9      2
94            5.6          2.7           4.2          1.3      1
59            5.2          2.7           3.9          1.4      1
111           6.4          2.7           5.3          1.9      2
82            5.8          2.7           3.9          1.2      1
67            5.8          2.7           4.1          1.0      1
..            ...          ...           ...          ...    ...
85            6.0          3.4           4.5          1.6      1
39            5.1          3.4           1.5          0.2      0
31            5.4          3.4           1.5          0.4      0
20            5.4          3.4           1.7          0.2      0
148           6.2          3.4           5.4          2.3      2
26            5.0          3.4           1.6          0.4      0
43            5.0          3.5           1.6          0.6      0
40            5.0          3.5           1.3          0.3      0
36            5.5          3.5           1.3          0.2      0
27            5.2          3.5           1.5          0.2      0
0             5.1          3.5           1.4          0.2      0
17            5.1          3.5           1.4          0.3      0
22            4.6          3.6           1.0          0.2      0
109           7.2          3.6           6.1          2.5      2
4             5.0          3.6           1.4          0.2      0
10            5.4          3.7           1.5          0.2      0
48            5.3          3.7           1.5          0.2      0
21            5.1          3.7           1.5          0.4      0
131           7.9          3.8           6.4          2.0      2
117           7.7          3.8           6.7          2.2      2
46            5.1          3.8           1.6          0.2      0
44            5.1          3.8           1.9          0.4      0
18            5.7          3.8           1.7          0.3      0
19            5.1          3.8           1.5          0.3      0
5             5.4          3.9           1.7          0.4      0
16            5.4          3.9           1.3          0.4      0
14            5.8          4.0           1.2          0.2      0
32            5.2          4.1           1.5          0.1      0
33            5.5          4.2           1.4          0.2      0
15            5.7          4.4          

In [78]:
#selecting certain rows
iris_dataframe_new[1:10]

sepal length  sepal width  petal length  petal width  class
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0
5           5.4          3.9           1.7          0.4      0
6           4.6          3.4           1.4          0.3      0
7           5.0          3.4           1.5          0.2      0
8           4.4          2.9           1.4          0.2      0
9           4.9          3.1           1.5          0.1      0

In [84]:
#selection by labels
iris_dataframe_new.loc[1:10, ['sepal length', 'petal length']]

sepal length  petal length
1            4.9           1.4
2            4.7           1.3
3            4.6           1.5
4            5.0           1.4
5            5.4           1.7
6            4.6           1.4
7            5.0           1.5
8            4.4           1.4
9            4.9           1.5
10           5.4           1.5

In [85]:
#selection by locations
iris_dataframe_new.iloc[1:10, [0,2]]

sepal length  petal length
1           4.9           1.4
2           4.7           1.3
3           4.6           1.5
4           5.0           1.4
5           5.4           1.7
6           4.6           1.4
7           5.0           1.5
8           4.4           1.4
9           4.9           1.5

In [88]:
#masking by a single column values
iris_dataframe_new[iris_dataframe_new['sepal length'] > 7]

sepal length  sepal width  petal length  petal width  class
102           7.1          3.0           5.9          2.1      2
105           7.6          3.0           6.6          2.1      2
107           7.3          2.9           6.3          1.8      2
109           7.2          3.6           6.1          2.5      2
117           7.7          3.8           6.7          2.2      2
118           7.7          2.6           6.9          2.3      2
122           7.7          2.8           6.7          2.0      2
125           7.2          3.2           6.0          1.8      2
129           7.2          3.0           5.8          1.6      2
130           7.4          2.8           6.1          1.9      2
131           7.9          3.8           6.4          2.0      2
135           7.7          3.0           6.1          2.3      2

In [95]:
#filtering the dataframe using isin function 
iris_dataframe_new[iris_dataframe_new['sepal length'].isin([7.2])]

sepal length  sepal width  petal length  petal width  class
109           7.2          3.6           6.1          2.5      2
125           7.2          3.2           6.0          1.8      2
129           7.2          3.0           5.8          1.6      2

In [97]:
#applying functions
iris_dataframe_new['sepal length'].apply(lambda x : x**2).head()

0    26.01
1    24.01
2    22.09
3    21.16
4    25.00
Name: sepal length, dtype: float64

In [99]:
iris_dataframe_new.apply(lambda x : x**2).head()

sepal length  sepal width  petal length  petal width  class
0         26.01        12.25          1.96         0.04      0
1         24.01         9.00          1.96         0.04      0
2         22.09        10.24          1.69         0.04      0
3         21.16         9.61          2.25         0.04      0
4         25.00        12.96          1.96         0.04      0